//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db : DbContext
    {
        public db()
            : base("name=db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alerts> alerts { get; set; }
        public DbSet<config_devices> config_devices { get; set; }
        public DbSet<config_traffic_lights> config_traffic_lights { get; set; }
        public DbSet<enterprises> enterprises { get; set; }
        public DbSet<files> files { get; set; }
        public DbSet<log_assing_task> log_assing_task { get; set; }
        public DbSet<log_task> log_task { get; set; }
        public DbSet<messages> messages { get; set; }
        public DbSet<modules> modules { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<roles_modules> roles_modules { get; set; }
        public DbSet<task_statuses> task_statuses { get; set; }
        public DbSet<tasks> tasks { get; set; }
        public DbSet<tasks_relations> tasks_relations { get; set; }
        public DbSet<templates> templates { get; set; }
        public DbSet<templates_tasks> templates_tasks { get; set; }
        public DbSet<types_alerts> types_alerts { get; set; }
        public DbSet<units> units { get; set; }
        public DbSet<users> users { get; set; }
    }
}
