//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_modules
    {
        public decimal id { get; set; }
        public decimal rol_id { get; set; }
        public decimal module_id { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual modules modules { get; set; }
    }
}
