//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        public tasks()
        {
            this.alerts = new HashSet<alerts>();
            this.files = new HashSet<files>();
            this.log_assing_task = new HashSet<log_assing_task>();
            this.log_task = new HashSet<log_task>();
            this.messages = new HashSet<messages>();
            this.tasks_relations = new HashSet<tasks_relations>();
            this.tasks_relations1 = new HashSet<tasks_relations>();
        }
    
        public decimal id { get; set; }
        public decimal creator_user_id { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string task_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> father_taks_id { get; set; }
        public Nullable<decimal> process_id { get; set; }
    
        public virtual ICollection<alerts> alerts { get; set; }
        public virtual ICollection<files> files { get; set; }
        public virtual ICollection<log_assing_task> log_assing_task { get; set; }
        public virtual ICollection<log_task> log_task { get; set; }
        public virtual ICollection<messages> messages { get; set; }
        public virtual process process { get; set; }
        public virtual users users { get; set; }
        public virtual ICollection<tasks_relations> tasks_relations { get; set; }
        public virtual ICollection<tasks_relations> tasks_relations1 { get; set; }
    }
}
