//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class templates_tasks
    {
        public decimal id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public decimal template_id { get; set; }
        public string task_status_code { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public Nullable<decimal> user_id { get; set; }
    
        public virtual task_statuses task_statuses { get; set; }
        public virtual templates templates { get; set; }
        public virtual users users { get; set; }
    }
}
