//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.log_assing_task = new HashSet<log_assing_task>();
            this.log_task = new HashSet<log_task>();
            this.messages = new HashSet<messages>();
            this.tasks = new HashSet<tasks>();
            this.units1 = new HashSet<units>();
        }
    
        public decimal id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public decimal rol_id { get; set; }
        public Nullable<decimal> unit_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> state { get; set; }
        public string token_session { get; set; }
        public Nullable<decimal> enterprise_id { get; set; }
    
        public virtual enterprises enterprises { get; set; }
        public virtual ICollection<log_assing_task> log_assing_task { get; set; }
        public virtual ICollection<log_task> log_task { get; set; }
        public virtual ICollection<messages> messages { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<tasks> tasks { get; set; }
        public virtual units units { get; set; }
        public virtual ICollection<units> units1 { get; set; }
    }
}
